### ISSUE TITLE
Shader compilation error, Mac os 10.13.1

### ISSUE THREAD

**Issue by McGittyHub** [alexheretic/gfx-glyph#13]
Getting this shader compilation error when running my program using gfx_glpyh on my mac.

Works purrfectly on my windoge-machine.

```
`Err` value: Program(Vertex(CompilationFailed("ERROR: 0:1: \'\' :version \'130\' is not supported\nERROR: 0:2: \'\' :  #versionrequired and missing.\n")))
```

My suggestion for a solution is to bump the gals version from 130 to 150..

**Comment by alexheretic** [comment]
It should be that if _150 (OpenGL 3.2)_ is supported then _130 (OpenGL 3.0)_ must also be supported. So I'd be surprised if switching to 150 helps. Have you tried that and it worked?

Otherwise it may be that your mac doesn't support OpenGL 3.0. I haven't got a mac to test myself, so let me know what you find out.

**Comment by McGittyHub** [comment]
Well my project is using other shaders targeting glsl ver. 150 core and those are no problem for my puny MacBook air 11" from 2015.

I think the problem is that mac os isn't supporting OpenGL < 3.2..

**Comment by alexheretic** [comment]
`0.6.4` is now available with `#version 150` shaders. Let me know if it works for you.
