### ISSUE TITLE
Paragraph example crashes with font-size -> 64860.1Error: StringError("Failed to create 32768x32768 glyph texture")

### ISSUE THREAD

**Issue by butitsnotme** [alexheretic/gfx-glyph#35]
I ran the paragraph example, zoomed in and out a bunch (basically continuously for about 90 seconds) and it exited with the error in the title.

Run on:
Linux hostname 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
(Ubuntu 18.04)
Running under KDE on X11

System is a Thinkpad X220T, with Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz, no dedicated graphics.

Let me know if you want any other info.

**Comment by alexheretic** [comment]
gfx_glyph quadruples the glyph texture size and recreates when the current texture size is not big enough to fit all the queued glyphs. So this error means it tried to up-size to 32768x32768 but failed.

However, why this example needs so much texture cache is more the issue. The new vertical alignments `VerticalAlign::Center` & `VerticalAlign::Bottom` always layout the full section because they need to use the full dimensions to shift the characters into centre/bottom. 

Currently it looks like the entire section including out-of-bounds glyphs is being sent to the texture-cache too, causing the large texture requirements. I should be able to improve this.

**Comment by alexheretic** [comment]
Ok I've filtered out-of-bound glyphs from the v-center, v-bottom layouts which should ease the texture-cache size requirements 35b005c8f4aa81161516d02d0214cec6c3f63a97. I've also limited the paragraph & performance examples max font-size which should prevent the reported error 81ed36a6859407933de8597133b97a239baefbbd.

@butitsnotme can you retry with current master?
